stages:
  - compile
  - test
  - package
  - deploy

before_script:
  - echo "Logging into the docker repo"
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

image: maven:latest

cache:
  key: "$CI_PIPELINE_ID"

compile:
  stage: compile
  script:
    - echo "Compiling project"
    - mvn compile

test:
   stage: test
   script:
    - echo "Running unit tests"
    - mvn test

package:
  stage: package
  script:
    - mvn clean install -DskipTests
    - echo "Building the docker Image"
    - docker build -t $CI_REGISTRY/eidas/sign-validation .
  except:
    - master

package_master:
  stage: package
  script:
    - mvn clean install -DskipTests
    - echo "Building the docker Image"
    - docker build -t $CI_REGISTRY/eidas/sign-validation .
  only:
    - master


deploy:
  stage: deploy
  script:
    - echo "Pushing the image to the docker hub"
    - docker push $CI_REGISTRY/eidas/sign-validation:latest
    - export HTTPS_PROXY="$HTTPS_PROXY_SERVER"
    - oc login https://$OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN
    - oc rollout latest dc/$OPENSHIFT_POD -n $OPENSHIFT_PROJECT

deploy_master:
  stage: deploy
  script:
    - echo "Pushing the image to the docker hub"
    - docker push $CI_REGISTRY/eidas/sign-validation:latest
  when: manual
  only:
    - master
