- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: signvalidationsettings
  data:
    CORS_ALLOWED_ORIGINS: >-
      http://localhost:3000,https://sign.ta.fts.bosa.belgium.be,https://idp.ta.fts.bosa.belgium.be,https://validate.ta.fts.bosa.belgium.be
    KEYSTORE_ENABLED: 'true'
    TSA_MOCK: 'false'
  spec:
    selector:
      deploymentconfig: signvalidation

- apiVersion: v1
  kind: ConfigMap
  metadata: 
    name: databaseconfig
  data:
    RESOURCES_PW: 
    RESOURCES_SCHEMA: schema_resources_adm
    RESOURCES_URL: 'jdbc:postgresql://'
    RESOURCES_USER: resources_adm
    SIGNING_PW: ''
    SIGNING_SCHEMA: schema_signing_adm
    SIGNING_URL: 'jdbc:postgresql://'
    SIGNING_USER: signing_adm
  spec:
    selector:
      deploymentconfig: signvalidation